travis:
  secure:
    BINSTAR_TOKEN: WKN3FIp9+OIq6yMpI0PldyBZjYpg86K+eXp5b82jXZ3wfVwtghNCzWzfSeJuFZISEeA2QKQyOf1ONJi07qhQWyInrfBIHA3G5M/5RrUkIOJ1J+iH+GX0WaOZkjZqWj3JtU8+4r9DxfIg9ss1usZR/qr8MsnPlwYZQh9kRTT3qoQ4+uFsm25LwDS3e3AgJWYWvMwF6m5STfw2jWpdKN8qojiaN1xixUAdB3i2DioBTwaPesI9QNK5N1rh1SJKbco6azd8yQvnpXsfD9PGla4eYWRZi/mBW33hFdiz0kECu514AFup4/eNPNXdiS3RB0A35UQpMG+jouwHCSsMu9euiWFRfDQQWKc8efx4sWZCcVcEloV4I5nicL3+suKdHWMStAZ4WjZcUpkhnI1tgBseFyxtJz4p9I7VED4RJFIUtRKVGWf2tKNxrf3Fy58SoSZGXjg3S+UebX4Rxdv6SJeQsS5nzSYM3k4JoiJ7e0a/c+5o18C975xXJ3YbAWlKIZyQSQtUxxW4/RG/WEQ7HYv6QlMJooi23y39vw1K2iXWJx+nq0xUG8FUqDfL0p6MKgDtj7xV5Ke+/YI+DzumMjaB48816JUQytbrOUZ+/Z+CHB0HRBe6YPbeWcY5nExVpjuubTQp0DX30XdDZbo7sRQpN+FYUHTITEnpMS84WHX3eSI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
