travis:
  secure:
    BINSTAR_TOKEN: FEVcDkD2VVvmu2wtwKejhwT/TrUyR98Tx6eRHzWD0/EXblSSn39Gr/kw4wgCOGT8zrnPz1MNtHYdR1O86ZnBHPppxTIBgDiE26CeVLEAGcadFyVBxZMiMv7v74y47i3zb863FLMCoU7daZ5uakkapiCjTAqpdS2maAlWXw6DU5P9dew1trhYbud0JbLnw6uIqsIBVpxr2fRwg39hX9Dmev5UX/QAF+CXI097nGgMDK1BOr16s1iPFOxRgE7Lg6eX38w1bPbcuI382XzWtvZgSjb0mzeqKoVkg8ibRCb8weKRkw2B+qm2fr541Odb2Ba4EgxFavm2qfmPgdIIiF9rPWAEtCL3kslBceQzc/PKTMXRTErTtSMVY/5B8s6hVW2Cawtooowltwnn18AZvyX/sVH8faDt+bydQSyg6dV4HsyrSZxmBrb/xCRivxufbJzd3JEGnzdbSmoNCRHWs4Sfgs844VnaMj7mpwp+A/PBl61wmtlzDgNbNmQVAVT2T8JasctMMo3fLQMhmgYexGkSosK0/5Ut/6/MVj2HkCDY5sTDnqywZ35eEvGKdXsFvGsuMtUQ4JfyYjh+36D4onm9bPc8/khotoKAo4DF1GQd0EpJx6uOZdY9MDbIbTTgdEN/tG33HFeZGY8Nx2Usth1o0IhInuskK5r278H7RoVeu5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
